#Fernando Fernández Iglesias

version: "2.2"
services:
  fw:
    image: dmz/fw 
    build: ./fw
    networks:
      extranet:
        ipv4_address: 10.5.35.1
      intranet:
        ipv4_address: 10.5.36.1
    privileged: true
    tty: true
    
  ext:
    image: dmz/ext
    build: ./extranet
    networks:
      extranet:
       ipv4_address: 10.5.35.20
    depends_on:
      - fw
    privileged: true
    tty: true
  
  int:
    image: dmz/int
    build: ./intranet
    networks:
      intranet:
       ipv4_address: 10.5.36.20
    depends_on:
      - fw
    privileged: true
    tty: true
  
networks: 
  extranet: 
    driver: bridge
    ipam:
     config:
      - subnet: 10.5.35.0/24
        gateway: 10.5.35.254

  intranet:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.36.0/24
        gateway: 10.5.36.254
