#Fernando Fernández Iglesias

version: "2.2"
services:
  fw:
    image: dmz/fw 
    build: ./fw
    networks:
      extranet:
        ipv4_address: 10.5.5.1
      intranet:
        ipv4_address: 10.5.6.1
    privileged: true
    tty: true
    
  ext:
    image: dmz/ext
    build: ./extranet
    networks:
      extranet:
       ipv4_address: 10.5.5.20
    depends_on:
      - fw
    privileged: true
    tty: true
  
  int:
    image: dmz/int
    build: ./intranet
    networks:
      intranet:
       ipv4_address: 10.5.6.20
    depends_on:
      - fw
    ports:
      - 80:80
    privileged: true
    tty: true
  
networks: 
  extranet: 
    driver: bridge
    ipam:
     config:
      - subnet: 10.5.5.0/24
        gateway: 10.5.5.254

  intranet:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.6.0/24
        gateway: 10.5.6.254
