#Fernando Fernández Iglesias

version: "2.2"
services:
  fw:
    image: dmz/fw 
    build: ./fw
    container_name: hulk_fw
    networks:
      extranet:
        ipv4_address: 10.5.3.1
      intranet:
        ipv4_address: 10.5.4.1
    privileged: true
    tty: true
    
  ext:
    image: dmz/ext
    build: ./extranet
    container_name: hulk_ext
    networks:
      extranet:
       ipv4_address: 10.5.3.20
    depends_on:
      - fw
    privileged: true
    tty: true
  
  int:
    image: dmz/int
    build: ./intranet
    container_name: hulk_int
    networks:
      intranet:
       ipv4_address: 10.5.4.20
    depends_on:
      - fw
    privileged: true
    tty: true
  
networks: 
  extranet: 
    driver: bridge
    ipam:
     config:
      - subnet: 10.5.3.0/24
        gateway: 10.5.3.254

  intranet:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.4.0/24
        gateway: 10.5.4.254
